name: Hamibytes CI

on:
  push:
    branches: [main]

jobs:
  build-and-push-hami-bytes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine build environment
        id: set-env
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "TAG_NAME=latest" >> $GITHUB_ENV
          else
            BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
            echo "TAG_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
          fi

      - name: Debug Environment Variables
        run: echo "TAG_NAME is ${{ env.TAG_NAME }}"

      - name: Ensure Dockerfile exists
        run: ls -l Dockerfile

      - name: Login to Docker Hub 🚢
        uses: docker/login-action@v3
        with:
          username: crypticmetadev
          password: ${{ secrets.DOCKERHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            crypticmetadev/hamivytes:${{ github.sha }}
            crypticmetadev/hamibytes:${{ env.TAG_NAME }}